### ISSUE TITLE
[RFC] Roadmap for electronic invoicing (Version 1)

### ISSUE THREAD

**Issue by max3903** [OCA/l10n-chile#15]
Separation/extraction of l10n_cl_electronic_invoicing:

- [x] l10n_cl_toponym - by @max3903 - #17 
* RUT

- [x] l10n_cl_sii_activity - by @max3903 - #18
* SII Activities

- [x] l10n_cl_sii_reference - by @max3903 - #24

* SII References: Models, views and data

- [ ] l10n_cl_stock_sii_reference

* Many2one on the stock.picking to SII References

- [ ] l10n_cl_sale_sii_reference

* Many2one on the sale.order to SII References
* Push the value to the invoice and delivery order when confirming

- [x] l10n_cl_invoicing_policy - by @max3903 - #25 

Add a selection field "Invoicing Policy" with:
* Ticket (Boleta) --> Only for individual. 1 invoice for each delivery order. Sign the invoice only.
* Invoice (Factura) --> Only for company. VAT is required. 1 invoice for each delivery order. Sign the invoice only. Required the customer PO # on the SO/Invoice.
* Electronic Guide (Guia Electronica) --> Only for company. 1 invoice at the end of the month for all the delivery orders of that month. Sign the delivery order and the invoice.

- [x] l10n_cl_account

Fields for invoicing without signature --> https://github.com/KonosCL/l10n_cl_invoice

- [x] connector_acp - by @max3903 - #19

* Common base for digital signature
* Integration with Authorized Certification Providers (SII, Xerox, etc)
Company
* Sign/Send: Odoo or a backend backend
** if Odoo, allow to select the SSL certificate
** if Backend, allow to select the backend
Allow to configure the list of document to sign/send

- [x] l10n_cl_sii_folio - by @max3903 - #27

Sequences
Folios

- [x] l10n_cl_dte_account - by @max3903 - #26 --> https://github.com/KonosCL/l10n_cl_dte

Electronic signing of:
* invoices, refunds --> DTE_v10.xsd
* tickets (boleta) --> EnvioBOLETA_v11.xsd
Sign/Send the invoices/refunds when they are validated
Request the document status and log the message in the invoice chatter
Add a backend for SII 
Add documents: invoice and ticket

- [x] connector_acp_xerox - by @max3903 - #29 

* Add a backend for Xerox
* List of of supported documents that can be signed by Xerox

- [x] l10n_cl_dte_stock - by @max3903 - #28 

Fields on stock.picking for signing:
* Shipping type (Tipo de despacho) --> Route. Based on the route, display other fields (Driver name, Driver VAT, etc).
* Reason for the transfer (Razon del traslado) 
sign/Send the delivery order if the customer's invoice policy is "Electronic Guide"
Electronic signing of:
* stock.picking --> DTE_v10.xsd

**Comment by max3903** [comment]
@nelsonramirezs I will need your help to determine in which module fields should be moved to.

**Comment by max3903** [comment]
Superseeded by #52
