### ISSUE TITLE
[RFC] Roadmap for electronic invoicing (Version 2)

### ISSUE THREAD

**Issue by max3903** [OCA/l10n-chile#52]
# l10n_cl_sii_reference_stock

- [ ] Many2one on the stock.picking to SII References

# l10n_cl_sii_reference_sale

- [ ] Many2one on the sale.order to SII References
- [ ]  Push the value to the invoice and delivery order when confirming

# l10n_cl_etd

- [ ] Implement the signature within Odoo using the SSL certificate
- [ ] Use QWeb to generate the XML file instead of Jinja2 to ease the extensibility (See #45)

# Any module

- [ ] Add unit tests

**Comment by nelsonramirezs** [comment]
l10n_cl_toponym
Implement document_number. This is basically VAT but in Chilean format. @max3903

**Comment by max3903** [comment]
@nelsonramirezs Eso, ya no esta?
https://github.com/OCA/l10n-chile/blob/12.0/l10n_cl_toponym/models/res_partner.py#L41

**Comment by nelsonramirezs** [comment]
@max3903 I don't see it the way they want to see it. Format 55.555.555-5 .
